/* Example code for Think OS.

Copyright 2014 Allen Downey
License: GNU GPLv3

*/

#include <stdio.h>
#include <stdlib.h>

#define SIZE 5

int *foo() {
    int i;
    int array[SIZE];

    //printf("%p\n", array);

    for (i=0; i<SIZE; i++) {
        array[i] = 42;
    }
    return array;
}

void bar() {
    int i;
    int array[SIZE];

    //printf("%p\n", array);

    for (i=0; i<SIZE; i++) {
        array[i] = i;
    }
}

int main()
{
    int i;
    int *array = foo();
    bar();

    for (i=0; i<SIZE; i++) {
        printf("%d\n", array[i]);
    }

    return 0;
}

//Part 2: Stack Allocated Data

/*Question 1.
When the main function is run, it creates a pointer thats points to the array
generated by the 'foo' function, which contains 5 values, all of which are 42.
Then, it calls bar, which is an array of 5 indices. Each value stored in the
array is the value of its index.
Finally, the main function prints the array generated by foo.
*/

/*Question 2.
The error is "function returns address of local variable"
When returning an array, which is a local variable in foo, what we actually
return is its address, which is no longer valid outside of foo.
*/

/*Question 3.
Output:
0x7ffd9e011480
0x7ffd9e011480
Segmentation fault (core dumped)

This results in a segmentation fault. This means that the main function is
attempting to access something that it cannot (ie a read-only piece of memeory
or some memory that no longer exists). In this case, it is trying to read the
the array generated by foo, which is a local variable that doesn't exist outside
of that function.
*/

/*Question 4.
This time the only output is a segmentation fault without the two printed
addresses.
*/
